name: Bump Version Number

on:
  workflow_call:
    inputs:
      update-type:
        description: "The type of update to apply"
        default: "patch"
        required: true
        type: string
      version-file:
        description: "The file containing the version number"
        default: "version.json"
        required: false
        type: string
      username:
        description: "The username to use for git"
        default: "ChaosCantrip [Automated]"
        required: false
        type: string
      email:
        description: "The email to use for git"
        default: "dev@chaoscantrip.com"
        required: false
        type: string

jobs:
  get-new-version-number:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.get-new-version-number.outputs.new-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   

      - name: Set up Git
        run: |
          git config user.name "${{ inputs.username }}"
          git config user.email "${{ inputs.email }}"

      - name: Get new version number
        id: get-new-version-number
        run: |
          VERSION=$(jq -r '.version' version.json)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          echo "Current version: $VERSION"

          case "${{ inputs.update-type }}" in
              major)
              MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
              minor)
              MINOR=$((MINOR + 1)); PATCH=0 ;;
              patch)
              PATCH=$((PATCH + 1)) ;;
              *)
              echo "No valid bump type found"
              exit 1
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

  set-new-version-number:
    uses: ChaosCantrip/DestinyTCG/.github/workflows/set-version.yml@main
    needs: get-new-version-number
    with:
      version-number: ${{ needs.get-new-version-number.outputs.new_version }}
      version-file: ${{ inputs.version-file }}
      username: ${{ inputs.username }}
      email: ${{ inputs.email }}