name: Submodule Workflow

on:
  workflow_call:
    inputs:
      username:
        description: "The username to use for git"
        default: "ChaosCantrip [Automated]"
        required: false
        type: string
      email:
        description: "The email to use for git"
        default: "dev@chaoscantrip.com"
        required: false
        type: string
      version_file:
        description: "The file containing the version number"
        default: "version.json"
        required: false
        type: string
      pr_number:
        description: "The pull request number to operate on"
        required: true
        type: number
      commit-sha:
          description: "The commit SHA to use for the submodule"
          required: true
          type: string
      submodule-reference:
          description: "The submodule reference to update"
          required: true
          type: string
    secrets:
        monorepo-read-pat:
            description: "The DestinyTCG Read PAT"
            required: true
        monorepo-write-pat:
            description: "The DestinyTCG Monorepo Write PAT"
            required: true

jobs:
  bump-version-number:
    uses: ChaosCantrip/DestinyTCG/.github/workflows/bump-version.yml@main
    with:
      pr_number: ${{ inputs.pr_number }}
      version_file: ${{ inputs.version_file }}
      username: ${{ inputs.username }}
      email: ${{ inputs.email }}


  update-dev:
    needs: bump-version-number
    uses: ChaosCantrip/DestinyTCG/.github/workflows/update-dev.yml@main
    with:
      username: ${{ inputs.username }}
      email: ${{ inputs.email }}


  update-monorepo:
    needs: update-dev
    uses: ChaosCantrip/DestinyTCG/.github/workflows/update-monorepo.yml@main
    with:
      commit-sha: ${{ inputs.commit-sha }}
      submodule-reference: ${{ inputs.submodule-reference }}
      username: ${{ inputs.username }}
      email: ${{ inputs.email }}
    secrets:
      monorepo-read-pat: ${{ secrets.monorepo-read-pat }}
      monorepo-write-pat: ${{ secrets.monorepo-write-pat }}